### ISSUE TITLE
hope can share the code of the paper

### ISSUE THREAD

**Issue by wyf0912** [mancinimassimiliano/mancinimassimiliano.github.io#1]
paper **BEST SOURCES FORWARD: DOMAIN GENERALIZATION THROUGH SOURCE-SPECIFIC NETS** is very attractive.  Could you share the code of  the paper? 
Thanks a lot!

**Comment by mancinimassimiliano** [comment]
Hi,

I uploaded a first release of the code. The code is in Caffe and the release contains the prototxt of the fully fine-tuned network I used for the PACS experiment. 

I plan to release either the all the prototxts and scripts or directly a PyTorch version of the approach in the future. 

Feel free to reach me by email for any questions regarding the work.

Best,
Massimiliano

**Comment by wyf0912** [comment]
very grateful~
